# Generated by Django 5.1.5 on 2025-01-29 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('github_link', models.CharField(max_length=254)),
            ],
        ),
    ]
